// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "ColorGrader2.h"

void ColorGrader2::cb_editor_red_i(CurveEditor2*, void*) {
  combine_curves();
}
void ColorGrader2::cb_editor_red(CurveEditor2* o, void* v) {
  ((ColorGrader2*)(o->parent()))->cb_editor_red_i(o,v);
}

void ColorGrader2::cb_editor_green_i(CurveEditor2*, void*) {
  combine_curves();
}
void ColorGrader2::cb_editor_green(CurveEditor2* o, void* v) {
  ((ColorGrader2*)(o->parent()))->cb_editor_green_i(o,v);
}

void ColorGrader2::cb_editor_blue_i(CurveEditor2*, void*) {
  combine_curves();
}
void ColorGrader2::cb_editor_blue(CurveEditor2* o, void* v) {
  ((ColorGrader2*)(o->parent()))->cb_editor_blue_i(o,v);
}

void ColorGrader2::cb_editor_master_i(CurveEditor2*, void*) {
  combine_curves();
}
void ColorGrader2::cb_editor_master(CurveEditor2* o, void* v) {
  ((ColorGrader2*)(o->parent()))->cb_editor_master_i(o,v);
}

void ColorGrader2::cb_Bypass_i(Fl_Check_Button* o, void*) {
  if ( o->value() ) {
	for (int i=0; i<256; ++i) {
		m_values_r[i] = i;
		m_values_g[i] = i;
		m_values_b[i] = i;
	}
	nle::g_videoView->redraw();
} else {
	combine_curves();
};
}
void ColorGrader2::cb_Bypass(Fl_Check_Button* o, void* v) {
  ((ColorGrader2*)(o->parent()))->cb_Bypass_i(o,v);
}
ColorGrader2::ColorGrader2(int X, int Y, int W, int H, const char *L)
  : Fl_Group(X, Y, W, H, L) {
  ColorGrader2 *o = this;
o->align(FL_ALIGN_TOP_LEFT);
{ CurveEditor2* o = editor_red = new CurveEditor2(5, 20, 145, 145, "Red");
  o->box(FL_DOWN_BOX);
  o->color(FL_BACKGROUND_COLOR);
  o->selection_color(FL_BACKGROUND_COLOR);
  o->labeltype(FL_NORMAL_LABEL);
  o->labelfont(1);
  o->labelsize(14);
  o->labelcolor((Fl_Color)1);
  o->callback((Fl_Callback*)cb_editor_red);
  o->align(FL_ALIGN_TOP_LEFT);
  o->when(FL_WHEN_RELEASE);
}
{ CurveEditor2* o = editor_green = new CurveEditor2(155, 20, 145, 145, "Green");
  o->box(FL_DOWN_BOX);
  o->color(FL_BACKGROUND_COLOR);
  o->selection_color(FL_BACKGROUND_COLOR);
  o->labeltype(FL_NORMAL_LABEL);
  o->labelfont(1);
  o->labelsize(14);
  o->labelcolor((Fl_Color)2);
  o->callback((Fl_Callback*)cb_editor_green);
  o->align(FL_ALIGN_TOP_LEFT);
  o->when(FL_WHEN_RELEASE);
}
{ CurveEditor2* o = editor_blue = new CurveEditor2(305, 20, 145, 145, "Blue");
  o->box(FL_DOWN_BOX);
  o->color(FL_BACKGROUND_COLOR);
  o->selection_color(FL_BACKGROUND_COLOR);
  o->labeltype(FL_NORMAL_LABEL);
  o->labelfont(1);
  o->labelsize(14);
  o->labelcolor((Fl_Color)4);
  o->callback((Fl_Callback*)cb_editor_blue);
  o->align(FL_ALIGN_TOP_LEFT);
  o->when(FL_WHEN_RELEASE);
}
{ CurveEditor2* o = editor_master = new CurveEditor2(455, 20, 145, 145, "Master");
  o->box(FL_DOWN_BOX);
  o->color(FL_BACKGROUND_COLOR);
  o->selection_color(FL_BACKGROUND_COLOR);
  o->labeltype(FL_NORMAL_LABEL);
  o->labelfont(1);
  o->labelsize(14);
  o->labelcolor(FL_FOREGROUND_COLOR);
  o->callback((Fl_Callback*)cb_editor_master);
  o->align(FL_ALIGN_TOP_LEFT);
  o->when(FL_WHEN_RELEASE);
}
{ Fl_Check_Button* o = new Fl_Check_Button(5, 170, 85, 25, "Bypass");
  o->down_box(FL_DOWN_BOX);
  o->callback((Fl_Callback*)cb_Bypass);
}
end();
}

void ColorGrader2::combine_curves() {
  unsigned char* red = editor_red->m_values;
unsigned char* green = editor_green->m_values;
unsigned char* blue = editor_blue->m_values;
unsigned char* master = editor_master->m_values;

unsigned char* out_r = m_values_r;
unsigned char* out_g = m_values_g;
unsigned char* out_b = m_values_b;


for ( int i = 0; i < 256; i++ ) {
	out_r[i] = master[red[i]];
	out_g[i] = master[green[i]];
	out_b[i] = master[blue[i]];
}
nle::g_videoView->redraw();
}
