// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef ColorGrader2_h
#define ColorGrader2_h
#include <FL/Fl.H>
#include <FL/Fl_Group.H>
#include "CurveEditor2.H"
#include "globals.H"
#include "VideoViewGL.H"
#include <FL/Fl_Check_Button.H>

class ColorGrader2 : public Fl_Group {
public:
  ColorGrader2(int X, int Y, int W, int H, const char *L = 0);
  CurveEditor2 *editor_red;
private:
  void cb_editor_red_i(CurveEditor2*, void*);
  static void cb_editor_red(CurveEditor2*, void*);
public:
  CurveEditor2 *editor_green;
private:
  void cb_editor_green_i(CurveEditor2*, void*);
  static void cb_editor_green(CurveEditor2*, void*);
public:
  CurveEditor2 *editor_blue;
private:
  void cb_editor_blue_i(CurveEditor2*, void*);
  static void cb_editor_blue(CurveEditor2*, void*);
public:
  CurveEditor2 *editor_master;
private:
  void cb_editor_master_i(CurveEditor2*, void*);
  static void cb_editor_master(CurveEditor2*, void*);
  void cb_Bypass_i(Fl_Check_Button*, void*);
  static void cb_Bypass(Fl_Check_Button*, void*);
public:
  unsigned char* m_values_r;
  unsigned char* m_values_g;
  unsigned char* m_values_b;
  void combine_curves();
};
#endif
