// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "FilterItemWidget.H"
#include "FilterBase.H"

namespace nle
{

FilterItemWidget::FilterItemWidget(int X, int Y, int W, int H, const char *L)
  : Fl_Group(X, Y, W, H, L) {
  FilterItemWidget *o = this;
new Fl_Button(X+0, Y+0, 20, 20, "@2>");
{ Fl_Check_Button* o = new Fl_Check_Button(X+20, Y+0, 20, 20);
  o->down_box(FL_DOWN_BOX);
  o->value(1);
}
{ Fl_Box* o = m_filter_name = new Fl_Box(X+40, Y+0, 330, 20, "Filter Name");
  o->labelsize(12);
  o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  Fl_Group::current()->resizable(o);
}
new Fl_Button(X+370, Y+0, 20, 20, "@2>");
new Fl_Button(X+390, Y+0, 20, 20, "@8>");
new Fl_Button(X+410, Y+0, 20, 20, "@-11+");
end();
}
void FilterItemWidget::setFilter( FilterBase* filter )
{
	m_filter_name->label( filter->name() );
}

} /* namespace nle */
