// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "LiftGammaGainWidget.H"
LiftGammaGainWidget::LiftGammaGainWidget(int X, int Y, int W, int H, const char *L)
  : Fl_Group(X, Y, W, H, L) {
  LiftGammaGainWidget *o = this;
end();
}
